sudo: required
services:
    - docker

before_install:
    - docker build -t kolabayo360/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run kolabayo360/client-test npm test -- --coverage

after_success:
    - docker build -t kolabayo360/multi-client ./client
    - docker build -t kolabayo360/multi-nginx ./nginx
    - docker build -t kolabayo360/multi-server ./server
    - docker build -t kolabayo360/multi-worker ./worker
    #login to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push kolabayo360/multi-client
    - docker push kolabayo360/multi-nginx
    - docker push kolabayo360/multi-server
    - docker push kolabayo360/multi-worker